/*----------------------------------( CMQ )----------------------------------*/

/**
* Combine matching media queries into one media query definition.
* Useful for CSS generated by preprocessors using nested media queries.
*
* @see https://github.com/buildingblocks/grunt-combine-media-queries
*
*/

module.exports.tasks = {

    // combine media queries
    cmq: {
        options: {
            log: false
        },
        styles: {
            files: {
                '<%=config.css.tempDirConcat%>/<%=config.css.tempDevConcatFile%>': [ '<%=config.css.tempDirConcat%>/<%=config.css.tempDevConcatFile%>' ]
            }
        },
        vendor: {
            files: {
                '<%=config.css.tempDirConcat%>/<%=config.css.tempVendorConcatFile%>': [ '<%=config.css.tempDirConcat%>/<%=config.css.tempVendorConcatFile%>' ]
            }
        }
    },

};
